### ISSUE TITLE
Plugin can't be imported from commonjs

### ISSUE THREAD

**Issue by n4bb12** [LyraSearch/plugin-parsedoc#12]
**Describe the bug**
The plugin doesn't work with commonjs projects.

I would switch to ESM if I could, but some popular open source projects don't
support ESM yet, for example https://github.com/facebook/docusaurus/issues/6520

**To Reproduce**
I tried out different ways of importing the plugin, without success.
You can find a minimal reproduction here: https://github.com/n4bb12/lyra-cjs-repro

**Expected behavior**
I can use the plugin with commonjs projects.

**Additional Context**
I don't have this issue with the persistence plugin.

**Versions**
- @lyrasearch/lyra: 0.4.1
- @lyrasearch/plugin-parsedoc: 0.0.5
- typescript: 4.9.4
- npm: 8.19.2
- node: 18.12.0
- OS: Windows 11

**Comment by ShogunPanda** [comment]
This should have been fixed in release 0.1.0. Can you please confirm?

**Comment by n4bb12** [comment]
Yes, it works with 0.1.0. Thank you
