### ISSUE TITLE
Type error using populateFromGlob

### ISSUE THREAD

**Issue by n4bb12** [LyraSearch/plugin-parsedoc#13]
**Describe the bug**

The code example in the docs
https://docs.lyrasearch.io/plugins/parsedoc-plugin#usage doesn't compile.

**To Reproduce**

Init a new project with lyra and parsedoc, type: module, typescript, etc.

Create `lyra.ts` with the following content (see [docs](https://docs.lyrasearch.io/plugins/parsedoc-plugin#usage)):

```ts
import { create, insert } from "@lyrasearch/lyra";
import { populateFromGlob, defaultHtmlSchema } from "@lyrasearch/plugin-parsedoc";

const db = await create({
  schema: defaultHtmlSchema,
});

await populateFromGlob(db, "docs/**/*.html");
```

Create `tsconfig.json` with the following content (essentially the same settings
as the @lyrasearch/plugin-parsedoc source):

```json
{
  "compilerOptions": {
    "lib": ["ESNext", "DOM"],
    "module": "ES2022",
    "moduleResolution": "node",
    "target": "ES2022"
  },
  "ts-node": {
    "esm": true
  }
}
```

Run the code:

```
$ npx ts-node lyra.ts
D:\Projects\n4bb12\lyra-cjs\node_modules\ts-node\src\index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
lyra.ts:8:24 - error TS2345: Argument of type 'import("D:/Projects/n4bb12/lyra-cjs/node_modules/@lyrasearch/lyra/dist/types").Lyra<{ readonly type: "string"; readonly content: "string"; readonly id: "string"; }>' is not assignable to parameter of type 'import("D:/Projects/n4bb12/lyra-cjs/node_modules/@lyrasearch/plugin-parsedoc/node_modules/@lyrasearch/lyra/dist/esm/src/lyra").Lyra<{ readonly type: "string"; readonly content: "string"; readonly id: "string"; }>'.
  Property 'nodes' is missing in type 'import("D:/Projects/n4bb12/lyra-cjs/node_modules/@lyrasearch/lyra/dist/types").Lyra<{ readonly type: "string"; readonly content: "string"; readonly id: "string"; }>' but required in type 'import("D:/Projects/n4bb12/lyra-cjs/node_modules/@lyrasearch/plugin-parsedoc/node_modules/@lyrasearch/lyra/dist/esm/src/lyra").Lyra<{ readonly type: "string"; readonly content: "string"; readonly id: "string"; }>'.

8 await populateFromGlob(db, "docs/**/*.html");
                         ~~

  node_modules/@lyrasearch/plugin-parsedoc/node_modules/@lyrasearch/lyra/dist/esm/src/lyra.d.ts:63:5
    63     nodes: Nodes;
           ~~~~~
    'nodes' is declared here.

    at createTSError (D:\Projects\n4bb12\lyra-cjs\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (D:\Projects\n4bb12\lyra-cjs\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (D:\Projects\n4bb12\lyra-cjs\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (D:\Projects\n4bb12\lyra-cjs\node_modules\ts-node\src\index.ts:1433:41)
    at transformSource (D:\Projects\n4bb12\lyra-cjs\node_modules\ts-node\src\esm.ts:400:37)
    at D:\Projects\n4bb12\lyra-cjs\node_modules\ts-node\src\esm.ts:278:53
    at async addShortCircuitFlag (D:\Projects\n4bb12\lyra-cjs\node_modules\ts-node\src\esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11) {
  diagnosticCodes: [ 2345 ]
}
```

**Expected behavior**
Regular use of the library and documented code examples should not lead to type errors.

**Screenshots**

<img width="1480" alt="2023-01-21 04_05_03-" src="https://user-images.githubusercontent.com/6810177/213841019-064a3407-3a55-4cb7-a7af-1e31011c22e3.png">

**Versions**
- @lyrasearch/lyra: 0.4.1
- @lyrasearch/plugin-parsedoc: 0.0.5
- typescript: 4.9.4
- npm: 8.19.2
- node: 18.12.0
- OS: Windows 11

**Comment by simoneb** [comment]
@Ceres6 can it be that this hasn't been updated to be compatible with latest lyra? 

In general though @micheleriva something failing purely for typing changes is wrong in my opinion. Now I'm not sure whether that's the case here, but if it is, we should try to avoid it and either we're very careful when making any type changes to avoid breaking the ecosystem even when in practice it wouldn't be functionally broken, or ditch types altogether. 

Lyra's public API is so simple that I would challenge a strict need for types, but I appreciate it's a late call and nonetheless probably not something you would consider anyway. Nonetheless I stand by my opinion that breakages due purely to type changes which wouldn't break any functionality otherwise, are silly at best.

**Comment by n4bb12** [comment]
@simoneb, thanks for looking into this. It might make things easier to maintain the official plugins and the main library in a single repository. Advantages:

- Refactorings in the main library seamlessly propagate to plugins and can be done all at once (avoid for example https://github.com/LyraSearch/plugin-data-persistence/issues/14).
-The main library and official plugins can be published simultaneously with a synchronized version number. This reduces publishing overhead and avoids plugin compatibility confusion.
- Type inconsistencies can be avoided.

A lot of modular or plugin-rich OSS projects (e.g. [docusaurus](https://github.com/facebook/docusaurus) seem to be doing well with this approach.

**Comment by simoneb** [comment]
Valid point @n4bb12, thanks for sharing. Let's hear Michele's thoughts

**Comment by Ceres6** [comment]
It probably is because the plugin needs to be updated.
I would suggest adding dependabot, but it doesn't work with pnpm so we would need a workaround or use something different.
I can take a look at it on Monday, but I don't think this is just a typing problem.

**Comment by micheleriva** [comment]
> @simoneb, thanks for looking into this. It might make things easier to maintain the official plugins and the main library in a single repository

I was thinking the same. We used to do that at the beginning, and now it's becoming more and more difficult to maintain everything.

For now, we need to fix incompatibilities in the ecosystem. Then, we'll look into moving everything into a well-managed monorepo or similar solutions.

@simoneb I'd propose you and @ShogunPanda a quick chat on Monday to discuss this and see if there are better options (CI process with GitHub packages on the main repo? Monorepo?) but then, let's make an ETA for solving this once and forever 🙂

**Comment by ShogunPanda** [comment]
Yes, let's chat about this tomorrow.

For now my opinion is to keep plugins separate: once we solve the problem for a package we can replicate the solution everywhere. 

In the future new plugin writers can take inspiration from us (read as: ruthlessly copy 😄) and avoid the same pain.
