### ISSUE TITLE
Link in repo sidebar is dead.

### ISSUE THREAD

**Issue by n4bb12** [LyraSearch/plugin-parsedoc#15]
<img width="414" alt="2023-01-25 18_00_09-LyraSearch_plugin-parsedoc_ Plugin to parse HTML and Markdown files into Lyra in" src="https://user-images.githubusercontent.com/6810177/214629718-85456ba1-1155-4959-bb83-4a9b666d5bd3.png">

<img width="539" alt="2023-01-25 18_00_30-Page Not Found _ Lyra✨" src="https://user-images.githubusercontent.com/6810177/214629712-c11d1fec-f253-4ee4-8ecb-a7818f48a716.png">

**Comment by ShogunPanda** [comment]
Fixed. Thanks for reporting it!
